# Generated by Django 3.1.2 on 2020-12-22 06:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(max_length=100, verbose_name="seller's email")),
                ('buyer_email', models.EmailField(max_length=100, verbose_name="Buyer's email")),
                ('parcel_no', models.IntegerField(max_length=3)),
                ('amount', models.IntegerField(verbose_name='Parcel No')),
                ('file_upload', models.FileField(upload_to='documents/')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'transfers',
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=100, verbose_name='Email')),
                ('parcel_no', models.CharField(max_length=10)),
                ('reason', models.TextField(max_length=200)),
                ('subdivision_date', models.DateTimeField(verbose_name=datetime.date)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'subdivisions',
                'db_table': 'subdivisions',
            },
        ),
    ]
