# Generated by Django 3.1.2 on 2020-12-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='owner',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='parcel_no',
            field=models.IntegerField(max_length=3, verbose_name='Parcel No'),
        ),
    ]
