# Generated by Django 3.1.2 on 2020-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20201222_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision_date',
            field=models.DateTimeField(),
        ),
    ]
