# Generated by Django 3.2 on 2021-04-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_user_profile'),
        ('transaction', '0004_auto_20201222_1024'),
    ]

    operations = [
    ]
