# Generated by Django 3.2 on 2021-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_merge_0002_user_profile_0004_auto_20201222_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='parcel_no',
            field=models.IntegerField(verbose_name='Parcel No'),
        ),
    ]
