# Generated by Django 3.1.2 on 2021-05-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210425_2007'),
        ('transaction', '0006_auto_20210420_0929'),
    ]

    operations = [
    ]
