# Generated by Django 3.1.2 on 2020-12-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'accounts', 'verbose_name_plural': 'accounts'},
        ),
    ]
